# Computer Aided Design with SolidWorks

In this workshop you will learn the basics of CAD (computer aided design) and designing 3D objects in SolidWorks.

## Starting Tutorials

We strongly recommend using a mouse to navigate SolidWorks.

1. Open SolidWorks by clicking on the appropriate icon on the desktop.

2. In the top left corner, start a new part by clicking "File -> New" or by clicking the white page icon in the top toolbar.

3. When prompted, select "New Part."

4. In the bottom right corner of the window, there should be a bar that says either "IPS" (Inch/Pound/Second) or "MMGS" (Millimeter/Gram/Second). Click on this bar and select "IPS". HURC will work almost exclusively in inches.

5. Now you are ready to begin constructing your part. In the top right corner, underneath the top toolbar, click "Extruded Boss/Base." The symbol for this is a yellow square with a smaller green square overlaid.

6. The window will prompt you to choose one of three planes to construct your part in: Top, Front, or Right. Select the "Front" plane.

7. We will be designing a door-stop that consists of two parts. This might seem to be a device that should just be one part. That's because it is, but this is a tutorial so just humor us.

8. You should now be in the "Edit Sketch" mode. Begin by drawing a line (select the "Line" tool from the toolbar on the top of the page) from the origin horizontally to the right. Do not worry about the length of this line at the moment.

9. Draw a second line also from the origin, extending at an arbitrary angle to the top right. Do not worry about the length of this line or the angle between the two lines.

10. Draw a third line connecting the two lines you have drawn previously. You should now have a triangle with one horizontal side pictured on your screen.

11. Deselect the "Line" tool. Do NOT click "Exit Sketch"

12. Click on the third line that you drew. On the left side of the screen, there should be the option to "Add Relation". Click on "vertical." You should now have a right triangle on your screen.

13. Hold down the right-click button on your mouse, move your mouse upward, then release the right-click button. You should now be in the "Smart Dimension" mode.

14. Click on the horizontal line. It will prompt you to input the desired length - input "2 in" or simply "2". Hit enter.

15. Click on the angled line. It will prompt you to input the desired length. Do NOT input a length; instead, click again on the horizontal line. This will allow you to define the angle between the lines. Set the angle to 20 degrees.

16. Click on "Exit Sketch" at the top left. You will be prompted to define the extrusion measurement (the depth of the 3D part). Set it to be "3/4 in" or simply "3/4". Or if it floats your boat "0.75". Hit enter.

17. You should now see a 3D wedge on your screen. You can manipulate your view of the wedge by pushing the mouse's scroll wheel in and moving the mouse or by hitting Ctrl + n, where n is any number between 1 and 8.

18. We are almost done with this part. Hit Ctrl + 4 or otherwise navigate to view the vertical end of the part.

19. On the top toolbar, click on "Hole Wizard." It will prompt you to choose a face on which to construct the hole. Select the vertical end currently in your view.

20. On the left-hand side, select "Tapped Hole" and set the thread sizes to be ANSI-inch. Then, select the option of "10-32".

21. Set the depth of the hole to be 0.5"

22. Click on the "Positions" tab. Click once anywhere on the selected face.

23. Use "Smart Dimension" (recall from earlier) to set the point to be 0.25" from the bottom of the stop, and 0.5" from the right.

24. You are done with this part! Create a new folder called "HURC tutorial_YOUR NAME" on the Desktop and save the part in that folder with the file name of "Door stop 1"

25. With the help of the HURC members present, create the part shown on the whiteboard. No step-by-step for this one, let's see how much you've learned! Save this part in the same folder and call it "Door stop 2"

26. Create an assembly! Click File -> New -> Assembly

27. Using "Insert Components", browse for either of the two parts created earlier. Then click in the view window to insert that part in the view.

28. Repeat step 27 for the other part.

29. "Mate" the two components by setting the bottom faces to be coincident, the vertical faces to be coincident, and the screw holes to be concentric.

30. Congratulations! You are done! Present your final product to the HURC board for evaluation.
